// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtp1ahsjsKTKWABgWnJcQ8bSufC2Bx2ps',
    appId: '1:1060579968258:web:3e74db2488116845ea2e1b',
    messagingSenderId: '1060579968258',
    projectId: 'task-management-apps-59849',
    authDomain: 'task-management-apps-59849.firebaseapp.com',
    storageBucket: 'task-management-apps-59849.appspot.com',
    measurementId: 'G-D3P4G15Z45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBojMI8H_F1PcaIw3NZWJRAmz5XQn47k',
    appId: '1:1060579968258:android:f8b0fdb233c1c7e0ea2e1b',
    messagingSenderId: '1060579968258',
    projectId: 'task-management-apps-59849',
    storageBucket: 'task-management-apps-59849.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWQkxkKxEkAD6bRWK35tjx3vVCOAW7B10',
    appId: '1:1060579968258:ios:ba9e27f1626e73d7ea2e1b',
    messagingSenderId: '1060579968258',
    projectId: 'task-management-apps-59849',
    storageBucket: 'task-management-apps-59849.appspot.com',
    androidClientId: '1060579968258-t0v4u4534v1s3ldbecipghosuprfpkli.apps.googleusercontent.com',
    iosClientId: '1060579968258-mq0mld8t186ued9spoah9bvij6ah85mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWQkxkKxEkAD6bRWK35tjx3vVCOAW7B10',
    appId: '1:1060579968258:ios:ba9e27f1626e73d7ea2e1b',
    messagingSenderId: '1060579968258',
    projectId: 'task-management-apps-59849',
    storageBucket: 'task-management-apps-59849.appspot.com',
    androidClientId: '1060579968258-t0v4u4534v1s3ldbecipghosuprfpkli.apps.googleusercontent.com',
    iosClientId: '1060579968258-mq0mld8t186ued9spoah9bvij6ah85mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
